// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUOx7iGeHXvwD1UDRsbsN0tpE2nSItd60',
    appId: '1:273043847146:web:27bcf4e24bff2cbcdba493',
    messagingSenderId: '273043847146',
    projectId: 'appadocaoanimais',
    authDomain: 'appadocaoanimais.firebaseapp.com',
    storageBucket: 'appadocaoanimais.firebasestorage.app',
    measurementId: 'G-BNS9WQY0KG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRJvZIz5C3eaDRQQnlacPxmsv4ZsUjFpQ',
    appId: '1:273043847146:android:4e052d59e6097f61dba493',
    messagingSenderId: '273043847146',
    projectId: 'appadocaoanimais',
    storageBucket: 'appadocaoanimais.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU9wUI3FqdMP4APtpcn1vn1rd1i9-ZUxg',
    appId: '1:273043847146:ios:8f4b12923a3179f7dba493',
    messagingSenderId: '273043847146',
    projectId: 'appadocaoanimais',
    storageBucket: 'appadocaoanimais.firebasestorage.app',
    iosBundleId: 'com.example.adocao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU9wUI3FqdMP4APtpcn1vn1rd1i9-ZUxg',
    appId: '1:273043847146:ios:8f4b12923a3179f7dba493',
    messagingSenderId: '273043847146',
    projectId: 'appadocaoanimais',
    storageBucket: 'appadocaoanimais.firebasestorage.app',
    iosBundleId: 'com.example.adocao',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUOx7iGeHXvwD1UDRsbsN0tpE2nSItd60',
    appId: '1:273043847146:web:23249ef839870850dba493',
    messagingSenderId: '273043847146',
    projectId: 'appadocaoanimais',
    authDomain: 'appadocaoanimais.firebaseapp.com',
    storageBucket: 'appadocaoanimais.firebasestorage.app',
    measurementId: 'G-QTVQ2Y2053',
  );
}
